{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix # generated by `nixos-generate-config`, keep as-is
  ];

  # ---- Bootloader: Limine, dual boot with Windows ----
  # Install Windows FIRST, shrink its partition, then install NixOS.
  # Limine is the modern bootloader CachyOS defaults to — BTRFS snapshot
  # integration, theming support, and reliable Windows EFI detection.
  boot.loader.limine.enable = true;
  boot.loader.limine.maxGenerations = 10; # keep last 10 generations in the menu
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot"; # confirm this matches your EFI partition mount

  # Uncomment to theme the boot menu (wallpaper + palette), Catppuccin-style:
  # boot.loader.limine.style.wallpapers = [ ./assets/limine-splash.png ];
  # boot.loader.limine.extraConfig = ''
  #   term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
  # '';

  networking.hostName = "desktop"; # must match the name in flake.nix
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Seoul"; # set ahead of the move — change now, or later, your call
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_TIME = "ko_KR.UTF-8"; # dates/currency formats once you're in Korea
  };
  i18n.supportedLocales = [ "en_US.UTF-8/UTF-8" "ko_KR.UTF-8/UTF-8" ];

  # ---- niri session ----
  # niri is packaged directly in nixpkgs unstable.
  programs.niri.enable = true;

  # Noctalia's own greeter: runs its own lightweight wlroots compositor
  # (rather than depending on GTK theming like regreet), and can sync your
  # wallpaper + color palette straight from the shell so the login screen
  # actually matches your desktop. Enables and configures greetd for you.
  programs.noctalia-greeter = {
    enable = true;
    greeter-args = "--session niri";
    settings = {
      keyboard = { layout = "us,kr"; };
    };
  };
  # After first login: Settings → Shell → Security → Noctalia Greeter →
  # Sync Now, inside the Noctalia shell itself, to push your wallpaper/palette
  # to the login screen.

  # polkit is required by the greeter/shell for privileged actions (power
  # profiles, network changes, etc.); accountsservice enables user avatars
  # in the login picker.
  security.polkit.enable = true;
  services.accounts-daemon.enable = true;

  # ---- GPU: NVIDIA Optimus/PRIME (Swift X = Intel/AMD + discrete NVIDIA) ----
  # This is the config that usually goes wrong on hybrid-graphics laptops —
  # follow the steps below in order, they matter.
  boot.kernelParams = [ "nvidia-drm.modeset=1" "nvidia-drm.fbdev=1" ];

  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true; # needed for Steam/Proton/most games

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true; # helps suspend/resume actually work on laptops
    open = true; # Turing (RTX 20xx) and newer support the open kernel modules — Swift X GPUs all qualify
    package = config.boot.kernelPackages.nvidiaPackages.stable;

    prime = {
      offload.enable = true; # GPU stays off until a game explicitly requests it — best for battery
      offload.enableOffloadCmd = true; # gives you the `nvidia-offload` wrapper command
      # CHANGE these two — find real values after first boot with `lspci | grep -E "VGA|3D"`
      # they'll look like "PCI:1:0:0" (note the colons, not dots, for NixOS's format)
      intelBusId = "PCI:0:2:0";   # or amdgpuBusId if this unit has an AMD CPU/iGPU instead
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Run a game with the dGPU explicitly: `nvidia-offload steam` (or set it as
  # Steam's launch wrapper per-game if you only want specific titles on the dGPU).

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "nvidia"; # hardware video decode through the NVIDIA driver
  };

  # ---- Fingerprint reader ----
  # Which stack you need depends on the exact sensor chip, which varies even
  # within the Swift X line. After first boot, run `lsusb` and check the vendor:
  #   Goodix    (27c6:xxxx) — usually needs libfprint-2-tod1-goodix (proprietary blob)
  #   Synaptics (06cb:xxxx) — usually needs python-validity, NOT plain libfprint
  #   ELAN      (04f3:xxxx) — best odds of just working with stock libfprint
  # Community driver/patch status for stubborn sensors:
  # https://github.com/jedbillyb/linux-fingerprint-drivers
  services.fprintd.enable = true;
  # Let fingerprint auth work for login + sudo once you've run `fprintd-enroll`
  security.pam.services.login.fprintAuth = true;
  security.pam.services.sudo.fprintAuth = true;
  # noctalia-greeter's PAM stack picks this up automatically once fprintd is enrolled.

  # ---- Audio ----
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
    jack.enable = true; # harmless to leave on even if you never use JACK apps
  };
  security.rtkit.enable = true; # required by pipewire for realtime scheduling

  # ---- Fonts: get Korean glyphs right before you need them ----
  fonts.packages = with pkgs; [
    noto-fonts-cjk-sans
    noto-fonts-cjk-serif
    noto-fonts-color-emoji
    pretendard # popular, very legible Korean/Latin variable font
    nerd-fonts.jetbrains-mono # for terminal/bar icons (Nerd Font glyphs)
  ];

  # ---- Korean input method ----
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.addons = with pkgs; [
      fcitx5-hangul
      fcitx5-gtk
    ];
  };

  programs.fish.enable = true;

  # ---- Users ----
  # CHANGE "bonobones" here to match flake.nix and home/home.nix
  users.users.tibo = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    shell = pkgs.fish; # or zsh/bash, your call
  };

  # allow the AUR-adjacent world (unfree packages like some fonts/drivers)
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "25.11"; # set to whatever version you installed with — do not change after install
}
